name: 'Build React App'
description: 'This action will build your React App.'
author: 'Ezequiel Leites <ezequiel@leites.dev>'

runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'git-commit'
  color: 'orange'